# Generated by Django 3.2.4 on 2021-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base64_image_url',
            field=models.TextField(blank=True),
        ),
    ]
