# Generated by Django 3.2.4 on 2021-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210710_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_stage',
            field=models.CharField(choices=[('S', 'Sale'), ('SO', 'Sold out')], default='S', max_length=2),
        ),
    ]
