# Generated by Django 3.2.4 on 2021-07-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_product_sales_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_stage',
        ),
    ]
