# Generated by Django 3.2.4 on 2021-08-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_product_sales_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
