# Generated by Django 3.2.4 on 2021-07-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_stage',
            field=models.CharField(choices=[('S', 'Sale'), ('SR', 'Sales Reservation'), ('SO', 'Sold out')], default='S', max_length=2),
        ),
    ]
