# Generated by Django 3.2.4 on 2021-08-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_order_sales_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating_check',
            field=models.BooleanField(default=False),
        ),
    ]
